pipeline:
  name: "feature_engineering"
  pkg_path: "feature_engineering.yaml"
  experiment: "train_bert_focal_loss"

components:
  columns: ['Narrative', 'Anomaly']
  enable_caching: True
  labels: ['Deviation / Discrepancy - Procedural',
  'Aircraft Equipment',
  'Conflict',
  'Inflight Event / Encounter',
  'ATC Issue',
  'Deviation - Altitude',
  'Deviation - Track / Heading',
  'Ground Event / Encounter',
  'Flight Deck / Cabin / Aircraft Event',
  'Ground Incursion',
  'Airspace Violation',
  'Deviation - Speed',
  'Ground Excursion',
  'No Specific Anomaly Occurred']
  target: "Anomaly"
  test_dataset: "test_data_final.pkl"
  train_dataset: "train_data_final.pkl"
  feature_group_version: 1
