steps: 
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "AIP_TENSORBOARD=$$AIP_TENSORBOARD" >> .env
        echo "ENDPOINT=$$ENDPOINT" >> .env
        echo "HOPSWORKS_API_KEY=$$HOPSWORKS_API_KEY" >> .env
        echo "HOPSWORKS_PROJECT=$$HOPSWORKS_PROJECT" >> .env
        echo "GPU_IMAGE=$LOCATION-docker.pkg.dev/$PROJECT_ID/${_IMAGE}:gpu"
        echo "IMAGE=$LOCATION-docker.pkg.dev/$PROJECT_ID/${_IMAGE}:cpu" >> .env
        echo "PIPELINE_ROOT=$$PIPELINE_ROOT" >> .env
        echo "PROJECT_ID=$PROJECT_ID" >> .env
        echo "RAW_DATA=$$RAW_DATA" >> .env
        echo "REGION=$LOCATION" >> .env
        docker login --username=$$DOCKERHUB_USERNAME --password=$$DOCKERHUB_TOKEN
        docker buildx create --name=container --driver=docker-container --use
        docker buildx build -f Dockerfile \
        -t ${_IMAGE}:${_DEVICE} \
        --builder=container \
        --platform=linux/amd64,linux/arm64 \
        --build-arg PYTHONVERSION=${_PYTHONVERSION} \
        --build-arg BASE_VERSION=${_BASE_VERSION} \
        --build-arg DEVICE=${_DEVICE} \
        --cache-to "type=registry,ref=${_IMAGE}:${_DEVICE}-cache,mode=max" \
        --cache-from "type=registry,ref=${_IMAGE}:${_DEVICE}-cache" \
        --load .
        docker tag ${_IMAGE}:${_DEVICE} $LOCATION-docker.pkg.dev/$PROJECT_ID/${_IMAGE}:${_DEVICE}
        docker push $LOCATION-docker.pkg.dev/$PROJECT_ID/${_IMAGE}:${_DEVICE}
        docker push ${_IMAGE}:${_DEVICE}
    timeout: '7200s'
    secretEnv:
      - AIP_TENSORBOARD
      - DOCKERHUB_USERNAME
      - DOCKERHUB_TOKEN
      - ENDPOINT
      - HOPSWORKS_API_KEY
      - HOPSWORKS_PROJECT
      - PIPELINE_ROOT
      - RAW_DATA
logsBucket: ${_LOG_BUCKET}
options:
  machineType: 'E2_HIGHCPU_8'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/AIP_TENSORBOARD_LOG_DIR/versions/1
    env: AIP_TENSORBOARD
  - versionName: projects/$PROJECT_NUMBER/secrets/DOCKERHUB_USERNAME/versions/1
    env: DOCKERHUB_USERNAME
  - versionName: projects/$PROJECT_NUMBER/secrets/DOCKERHUB_TOKEN/versions/1
    env: DOCKERHUB_TOKEN
  - versionName: projects/$PROJECT_NUMBER/secrets/ENDPOINT/versions/1
    env: ENDPOINT
  - versionName: projects/$PROJECT_NUMBER/secrets/HOPSWORKS_API_KEY/versions/1
    env: HOPSWORKS_API_KEY
  - versionName: projects/$PROJECT_NUMBER/secrets/HOPSWORKS_PROJECT/versions/1
    env: HOPSWORKS_PROJECT
  - versionName: projects/$PROJECT_NUMBER/secrets/PIPELINE_ROOT/versions/1
    env: PIPELINE_ROOT
  - versionName: projects/$PROJECT_NUMBER/secrets/RAW_DATA/versions/1
    env: RAW_DATA
