name: Build and Push images

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      - '!LICENCE'
      - 'README.md'
      - '!.gitignore'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-images-build-and-push-workflow:
    uses: ./.github/workflows/build_push_images_on_call.yaml
    secrets: inherit
    with:
      BASE_VERSION: ${{ vars.BASE_VERSION }}
      IMAGE: ${{ vars.IMAGE }}
      PYTHONVERSION: ${{ vars.PYTHONVERSION }}
