name: Build base image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Check if Dockerfile.base is modified
        id: check_base
        run: echo ::set-output name=modified::$(git diff --name-only HEAD^ HEAD Dockerfile.base)
      -
        name: Set up QEMU
        if: steps.check_base.outputs.modified != ''
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        if: steps.check_base.outputs.modified != ''
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        if: steps.check_base.outputs.modified != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        if: steps.check_base.outputs.modified != ''
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.base
          push: true
          tags: drxc/alpine_asrs_base:latest
          cache-from: type=registry,ref=drxc/alpine_asrs_base:buildcache
          cache-to: type=registry,ref=drxc/alpine_asrs_base:buildcache,mode=max