name: Docker Files CI

on:
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Create .env file based on Github Secrets
        uses: ozaytsev86/create-env-file-action@v1
        with:
          GCP_PIPELINES_ROOT: ${{ secrets.GCP_PIPELINES_ROOT }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_PROJECT_REGION: ${{ secrets.GCP_PROJECT_REGION }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT: ${{ secrets.HOPSWORKS_PROJECT }}
          IMAGE: ${{ secrets.IMAGE }}
          KUBEFLOW_HOST: ${{ secrets.KUBEFLOW_HOST }}
          KUBEFLOW_PIPELINES_ROOT: ${{ secrets.KUBEFLOW_PIPELINES_ROOT }}
          RAW_SOURCE: ${{ secrets.RAW_SOURCE }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.base
          push: False
          tags: drxc/alpine_asrs_base:test
          cache-from: type=registry,ref=drxc/asrs_base:buildcache
          cache-to: type=registry,ref=drxc/asrs_base:buildcache,mode=max
