name: Docker Files CI

on:
  pull_request:
    branches:
      - 'main'

jobs:
  docker-ci:
    strategy:
      matrix:
        DEVICE: ['cpu', 'gpu']
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Create .env file based on Github Secrets
        run: |
          echo "AIP_TENSORBOARD=${{ secrets.AIP_TENSORBOARD }}" >> .env
          echo "ENDPOINT=${{ secrets.ENDPOINT }}" >> .env
          echo "HOPSWORKS_API_KEY=${{ secrets.HOPSWORKS_API_KEY }}" >> .env
          echo "HOPSWORKS_PROJECT=${{ secrets.HOPSWORKS_PROJECT }}" >> .env
          echo "GPU_IMAGE=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ vars.IMAGE }}:gpu"
          echo "IMAGE=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ vars.IMAGE }}:cpu" >> .env
          echo "PIPELINE_ROOT=${{ secrets.PIPELINE_ROOT }}" >> .env
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> .env
          echo "RAW_DATA=${{ secrets.RAW_DATA }}" >> .env
          echo "REGION=${{ secrets.REGION }}" >> .env
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Images build test
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            PYTHONVERSION=${{ vars.PYTHONVERSION }}
            BASE_VERSION=${{ vars.BASE_VERSION }}
            DEVICE=${{ matrix.DEVICE }}
          file: Dockerfile
          push: true
          tags: |
            ${{ vars.IMAGE }}:${{ matrix.DEVICE}}
          cache-from: type=registry,ref=${{ vars.IMAGE }}:${{ matrix.DEVICE}}-cache
          cache-to: type=registry,ref=${{ vars.IMAGE }}:${{ matrix.DEVICE}}-cache,mode=max
